name: pkg-config
version: "0.30"
description: "Package configuration tool"
author: "Various"
license: "GPL-2.0-or-later"
homepage: "https://www.freedesktop.org/wiki/Software/pkg-config/"
repository: "https://gitlab.freedesktop.org/pkg-config/pkg-config"
keywords:
  - pkg-config
categories:
  - packages

dependencies:
  build_dependencies:
    - name: "gcc"
      version_constraint: ">=4.0"
      optional: false
    - name: "make"
      version_constraint: ">=3.0"
      optional: false
  runtime_dependencies: []
  optional_dependencies: []
  conflicts: []

build:
  build_system: Make
  build_commands:
    - "./configure --prefix=/usr"
    - "make"
  build_dependencies:
    - "gcc"
    - "make"
  build_flags: []
  environment:
    CFLAGS: "-O2"
  working_directory: null
  target_architectures:
    - X86_64v3
    - Aarch64
  cross_compiler_prefix: null
  target_sysroot: null

install:
  install_method: RunCommands
  install_commands:
    - "make install"
  install_directories:
    - "/usr/bin"
  install_files: []
  post_install_commands: []

files:
  include_patterns:
    - "*.c"
    - "*.h"
    - "configure"
    - "Makefile.in"
  exclude_patterns:
    - "**/*.o"
    - "**/*.a"
    - "tests/**/*"
    - ".git/**/*"
  binary_files: []
  config_files: []
  documentation_files: []
  license_files: []

scripts:
  pre_install: |
    echo "Installing pkg-config..."
  post_install: |
    echo "pkg-config installed successfully"
  pre_uninstall: |
    echo "Removing pkg-config..."
  post_uninstall: |
    echo "pkg-config removed successfully"
  pre_upgrade: null
  post_upgrade: null

metadata:
  maintainer: "Oreon Project Team <packaging@oreonproject.org>"
  section: "packages"
  priority: "optional"
  provides:
    - "pkg-config"
  conflicts: []
